name: "Multi event workflow/pipeline"

on:
  push:
    branches:
      - master
      - test
  pull_request:
    branches:
      - master

jobs:
  push_event_job:
    runs-on: ubuntu-latest
    steps:
      - name: "Step1 runs when push on master/test branch"
        run: echo "st1 triggered by push"

  pr_event_job:
    runs-on: ubuntu-latest
    steps:
      - name: "Step2 runs when PR on master branch"
        run: echo "st2 triggered by pull request"
